### ISSUE TITLE
Temperature conversion problem

### ISSUE THREAD

**Issue by elmo2k3** [sw-home/FHEM-BluetoothSmartBMS#2]
It seems there is something wrong with the temperature. Also when the temperature is below 0, there are no values any more.
![Screenshot_2019-12-28_22-21-27](https://user-images.githubusercontent.com/20565/71549610-a2cc9e80-29c0-11ea-9cd1-12f228a571d5.png)

Many many thanks for this project! Using it in my micro camper van.

**Comment by sw-home** [comment]
Hi sorry for that, the temperature data from BMS is somehow bogus. I spent a lot of time on making it better but it's still jerky. Unfortunately there is no official documentation on the protocols. 
I just draw dotted lines in my charts to hide it :)
